name: Check JSON Formatting

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check-json-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Validate JSON files
        run: |
          set -e
          find . -name "*.json" -print0 | xargs -0 -I{} python -m json.tool {} > /dev/null